### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by 3akev** [Durkastan/durkabot#1]
In order of priority:

- [ ] Book searching:
  - [ ] Waqfeya
  - [ ] Shamela
- [ ] Tags
- [ ] Dictionary
- [ ] Quran
- [ ] Hadith
- [ ] Mod Controls
  - [ ] Ban
  - [ ] Kick
  - [ ] Warn
  - [ ] Temp-ban with automatic unban after set time
  - [ ] Purge
  - [ ] Jail

**Comment by martomato** [comment]
is "Tags" the same as [this](https://github.com/Durkastan/durkabot/projects/1#card-10761471) (emote highlights)?

**Comment by martomato** [comment]
broke this issue down into [specific cards](https://github.com/Durkastan/durkabot/projects/1#column-2923694) -- closing this issue
